honeydipper/honeydipper-config-essentials

kubernetes/workflows.yaml
The data type workflow was added in v0.1.6, this the first case to use it.  This requires honeydipper/honeydipper#60
=> refactor(kubernetes): use data workflow to stitch return data

workflow_helper.yaml
By also checking the `.data.work_status`, the `pipe` workflow now can be nested.  Also, we can use `data` type workflow to return `failure` status  to break out of the pipe.  Tested locally.
=> feat(pipe): pipe workflow flow can be controlled using data

workflow_helper.yaml
By wrapping each step into a single step native `pipe` workflow, we get to mutate the workflow data and strip off the complicated logic in the `steps` before passing control to operator to make calls to drivers.  Without this, the operator service will attempt to interpolate data in `steps` which is not meant for consumption at that moment , causing interpolation errors.
=> bug(pipe): strip off steps before sending to operators

slack/workflows.yaml, workflow_helper.yaml
Attempt 2
* fixed a bug in daemon where trailing hook crash could result in crash looping, pushed to `DipperCL-rc3`
* The actual change made the `channel_translate` working is a pair of quotes here https://github.com/honeydipper/honeydipper-config-essentials/blob/0c1cadded84e2deb3a4e124f2b76141468eb6ae6/workflow_helper.yaml#L92
=> feat: translate channel names to ids

workflow_helper.yaml
* use `if/else` instead of `ternary` for safer parameter processing
* use `substr` instead of `trunc` for fetching content from tail of string
=> fix: use if else instead ternary for safer parameter processing

slack/systems.yaml, slack/workflows.yaml
slack is recommending the new `layout blocks` format for constructing messages. The `layout blocks` doesn't support `attachments` `color` indicator bar, so slack recommends to use `blocks` within `attachments`. Unfortunately, it seems still buggy, `color` doesn't work any more if there are `blocks` in `attachments`. For now, we will continue use `attachments` for announcement and status messages but allow workflows and functions to use blocks through `ctx.blocks`.
=> feat: using new slack blocks

kubernetes/contexts.yaml
When running `git-clone` in `run_kubernetes`, we can specify the git access in `sysData`. But it is not flexible enough.  Using `ctx` data is a lot of easier. This is backwards compatible.
=> feat: allowing specify git access info through ctx

kubernetes/workflows.yaml
This is helpful when running into transient errors.
=> feat: retrying get kube job status

github.yaml
Features: Support creating GH repo, and adding GH repo to installation
* Add create_repo() function
* Add Add_repo_to_installation() function
This added two functions into github system to create a github repo, and adding a github repo to a github installtion/app.
These two functions can be useful to create a workflow that create a brand new repo for your organization then immediately add that repo to a github installation (slack bot for example)
Example:
```
workflows:
github_create_repo:
steps:
- call_function: github.createRepo
with:
org: honeyscience
- call_function: github.addRepoToInstallation
with:
org: honeyscience
repoid: '{{ .ctx.repoid }}'
```
=> feat: create_repo, add_repo_to_installation func for github system

kubernetes/contexts.yaml
* hiding ssh-keyscan and ssh-add outputs
* git push only when new commits are present
* output an indicator if skipping git push
=> feat: enhancing k8s git clone and push steps

kubernetes/contexts.yaml
The `git_ref` context variable contains the ref name as `refs/heads/<name>`, but the clone command running in k8s job only needs the name part.  So, use `base` function from sprig http://masterminds.github.io/sprig/paths.html to strip the path.
=> fix: branch name should be the base name of the ref

kubernetes/contexts.yaml
`base` method return a dot "." when the provided path is empty. We dont need that dot.
=> fix: return blank string when .ctx.git_ref is blank

kubernetes/system.yaml, kubernetes/workflows.yaml
Since the `TTLSecondsAfterFinish` is stuck in alpha as of kubernetes 1.18, we need a way to clean up the finished jobs. Since `honeydipper` `1.4.0`, the `deleteJob` feature is added to the driver.  By adding this, the `run_kubernetes` workflow itself will take care of the clean up.
=> feat(k8s): delete jobs upon successful completion

gcloud/init.yaml, gcloud/systems.yaml, github.yaml, kubernetes/system.yaml, slack/systems.yaml, workflow_helper.yaml
This allows the workflow status message to display links, if the workflow exports a `links` context variable.
~~This PR goes hand in hand with honeydipper/honeydipper#249 . But, it can be shipped separately as it won't break anything. If `links` context variable is not defined, the behavior won't change.~~
The implementation of the links are done on the `system` level, and this is enabled by PR honeydipper/honeydipper#252 in version `1.5.0`.
=> feat(notify): enable displaying links in the workflow status

gcloud/systems.yaml
The link will break if namespace is not specified.
=> fix(gcloud): k8s job log link with default namespace

gcloud/systems.yaml, kubernetes/system.yaml
We may have different jobs in the workflow, and the links may overlap.
=> fix(gcloud): distinguish different job links

github.yaml
This reverts commit 8d41d1f0a7974f279e5ff78721a352c7e3ba5eea.
The original change was meant to go with another honeydipper code refactoring change,
however that refactoring was suspended. It broke all the github functions.
=> revert: refactor(github): adjusting function inheritance

slack/contexts.yaml, slack/workflows.yaml
Override the `hooks` for the `slashcommand/execute` workflow will change when/how the
status message is sent.
=> feat(slack): allow disable the slashcommand status through contexts

kubernetes/workflows.yaml
* longer jobs, such as db scrubbing taking days, need more retry during watching period.
=> fix(kubernetes): make waitForJob retry variable

slack/workflows.yaml
When moving the execution to the `slashcommand/execute` workflow, the status message
shows the new workflow name `slashcommand/execute` instead of the actual
workflow for the command. We can override this by setting the `description`
with the name of the actual workflow.
=> fix(slack): the slash command status message should show actual wf name

jira.yaml
Turns out that the current stable version for the atlassian API is 2,
and the version 3 [Atlassian Document Format](https://developer.atlassian.com/cloud/jira/platform/apis/document/structure/)
is really hard to use. I don't like the version 3. I think they should
maintain compatibility to version 2 document formatting approach in the
future.
=> fix(jira): use current API stable version 2

kubernetes/resources/honeydipper-job.yaml.tmpl
* a generic identifying label for getting all honeydipper created
* unique identifier for each job to avoid creating duplicates
With the identifying label, it is easier to maintain them in batch. For example:
```
kubectl delete pods -l creator=honeydipper --field-selector status.phase!=Running,status.phase!=Pending,status.phase!=Unknown
```
To identify one
```
kubectl get jobs -l honeydipper-unique-identifier=restoring-users-staging
```
=> feat(k8s): adding labels to job

kubernetes/resources/honeydipper-job.yaml.tmpl, kubernetes/workflows.yaml
Previously, the `backoffLimit` was hardcoded as 1, meaning the job will
retry the work once if the pod fails. This change makes it a variable so
we can adjust it as needed, and set the default to 0 for not retrying.
=> feat(k8s): allow k8s job with variable backoffLimit

daemon.yaml, gcloud/drivers.yaml, workflow_helper.yaml
BREAKING CHANGE: The new driver settings breaks all honeydipper `1.x.x`
deployments since the new driver binaries are not present in old docker
images.  b5ae89e
BREAKING CHANGE: The new changes break all honeydipper `1.x.x`
deployments. a3d8475
* fix: accomodate new release breaking changes
* feat: enabling API service
=> fix: supporting honeydipper 2.0.0

github.yaml
* calls the api at https://developer.github.com/v3/repos/#get-a-repository
* exports the result as `repo` and `id` as `repoid`
=> feat(github): adding a function to get Repo info

github.yaml
It is easier to use a string as `repoid`. Or, In some places, the
template will convert that into a scientific notation representation.
=> fix(github): converting repoid number to string

slack/workflows.yaml
Slashcommand uses `slash_notify` to specify the recipients, and should avoid
using `workflow_status` directly, which will only honor `notify` and `notify_on_error`.
=> fix(slack): correct slash command status message recipient

slack/workflows.yaml
Slack `response_url` expires in 30 minutes. To send slash command status feedback
we should use the name of the channel instead of using `reply`. Also simplify the
use of `slash_notify` and `channel_translate`.
=> fix(slack): slack response_url expires

circleci.yaml, init.yaml
* Capabililty to make API to trigger a pipeline.
CircleCI announced their [v2 API](https://circleci.com/blog/introducing-circleci-api-v2/) last year. It is
possible to take advantage of this to make the
integration to circleci workflows smoother.
=> feat(circleci): integrating with circleci

circleci.yaml
This only affects the generated documents on readthedoc.io.
=> fix(circleci): typo in docs

kubernetes/contexts.yaml, kubernetes/resources/honeydipper-job.yaml.tmpl
The `light` tag doesnt get updated once the image is downloaded
causing the inconsistency between nodes in kubernetes clusters.
This change allows customizing the `imagePullPolicy` for each
script type. And, we can use `Always` pull for tf script.
=> fix(kubernetes): tf script type imagePullPolicy Always

daemon.yaml
Adding docs for TLS configuration for redis drivers. To be merged before https://github.com/honeydipper/honeydipper/pull/371 is released so it makes into the sphinx release.
=> docs: redis drivers supporting TLS

slack/workflows.yaml
Right now, slashcommand status messages in private channels are missing
because we use `channel_fullname` to send feedback. But, the
`channel_fullname` will be `#privategroup` for all the private channels.
Switching to `channel_id` should fix this.
=> fix(slack): slashcommand send status use channel id

slack/workflows.yaml, workflow_helper.yaml
If the slash command is from private channel or direct message, we
should use the `channel_id` to send reply but if it is a public channel,
we should use the `channel_fullname` so the list of channels can be
properly deduped.
Also updated `channel_translate` with one more `uniq` function on the
output to ensure that the final list of `channel_ids` are all unique.
=> fix(slack): slashcommand status message dedupe

gcloud/drivers.yaml
Since Honeydipper version 2.3.0, a driver has been added to fetch
items from google secret manager.
=> feat(gcloud): add gcloud-secret driver and docs

kubernetes/contexts.yaml, kubernetes/resources/honeydipper-job.yaml.tmpl, kubernetes/workflows.yaml
[Berglas](https://github.com/GoogleCloudPlatform/berglas) is an utility
commonly used for handling secrets in kubernetes. It can be used as a
CLI tool, an administration controller or a library.
If `.ctx.berglas_files` is defined, there will be a step to fetch the
secrets and put them into designated files, and ensure the ownership,
mode and directory mode.
Also included in this PR, is the capability to name the kubernetes jobs
with customized prefixes instead of `honeydipper-job-`.
This is a portion from the original PR #107 that doesn't involve copying
the berglas binary and use it as entry point to handle secrets in
environment variables.
=> feat(kubernetes): handle secret files with berglas

kubernetes/resources/honeydipper-job.yaml.tmpl
The dollar interpolation won't work in the template files, so switch to
use go templating.
=> fix(kubernetes): generateName use go template

kubernetes/contexts.yaml
The command entry point should be empty.
=> fix(kubernetes): correct gcloud/cloud-sdk command entry point

init.yaml, opsgenie.yaml, pagerduty.yaml
Add pagerduty system to support webhook, snooze and whoisoncall. The
whoisoncall is standardized with a workflow so `OpsGenie` and `pagerduty`
can work similarly.
`pagerduty` doesnt support heartbeat feature as of now.
=> feat: support pagerduty integration

pagerduty.yaml
When sending web request, all data needs to be string. `whoisoncall` is
failing when multiple page of api result is encountered due to not
recognizing the `offset`.
=> fix(pagerduty): web form data must be string

pagerduty.yaml
When appending ctx list data, it needs to be done in workflow export
instead of function export.
=> fix(pagerduty): appending ctx data in workflow

gcloud/dataflow.yaml
If timed out when draining a dataflow job, will escalate the request to cancel the job.
Also, improve with granular control on timeouts for draining and cancelling.
=> feat(gcloud): dataflow draining fallback to cancelling

datadog/init.yaml
Previously, datadog can only be used through RPC. With the new
system, we should be able to use the features in workflows.
=> feat(datadog): add datadog system and functions

datadog/init.yaml
With more tag, we can create the monitor in Datadog easily.
=> feat(datadog): add more tags to heartbeat metric

slack/workflows.yaml
The status of the slash command should use in-channel reply messages to be
consistent with the announcement. For longer running slash commands, the status
message should sent to a slash_notify channel.
=> fix(slack): improve slash command experience

pagerduty.yaml
The value could be a single string or a list of strings.
=> fix(pagerduty): signatureSecret should not have default value

datadog/init.yaml
Grouping heartbeats using owner as metric suffix to avoid interferences
between the heartbeats, such as mistakenly emitting a gauge instead of a
counter value causing all heartbeats to flip.
=> feat(datadog): heartbeat metric groups with owner

circleci.yaml, codeclimate/systems.yaml, codeclimate/workflows.yaml
CircleCI system functions used to take only `git_repo` input variable
that represents the whole slug `org/repo`. Now, you can specify `repo`
with name only and use the system default org.
CodeClimate system functions used to take every input from `.ctx`, now
we can set the `org_id` and `org` at the system level as default value.
When they are missing in `.ctx`, system default will be used.
=> feat: setting default org and org_id in systems

codeclimate/systems.yaml
The web driver only parse json blob when the content type is exactly
`application/json`. Some of the APIs return with
`application/vnd.api+json`, and the content is not parsed. So we have to
manually parse the content into a object using `DipperCL`, then extract
the `repo_info`.
This should be fixed in the web driver code itself. This is just a
temporary workaround, and will be removed once the fix is implemented in
driver.
=> fix: extract repo_info from api result

slack/systems.yaml
Allow specify text in the slack message besides using blocks.
=> feat(slack): allow specify text besides blocks in messages

github.yaml
Sometimes the full commit hash is used for identifying a commit or
tagging an image. Making it available through export.
=> feat(github): export git_commit_full

kubernetes/workflows.yaml
Allow running a workflow when a kubernetes job is created. Useful when
we need to send notifications with job ID, name or link to the logs etc.
=> feat(k8s): on_job_start hook

slack/rules.yaml, workflow_helper.yaml
* accepting block_id from block action messages (new block style UI)
* muting the resume_workflow
* injecting the resume_token in the right place in the data structure
=> fix: slack interactive message support

gcloud/contexts.yaml, gcloud/workflows.yaml
Besides using k8s secret to setup gcloud credentials, using berglas to
fetch secrets at runtime is also supported.
=> feat(gcloud): setup gcloud credential in k8s jobs using berglas

slack/systems.yaml, workflow_helper.yaml
When replying to a slack interactive payload, slack will, by default, overwrite the existing message. We need a method to send a new message without overwriting the existing one.
=> fix: add a method for not overwriting interactive message

kubernetes/contexts.yaml, kubernetes/workflows.yaml
Have to introduce a step named `inject_misc_steps` to check the processed steps and find all `berglas_files`. Otherwise, the `berglas_files` in the steps or predefined steps wont work.
=> fix(kubernetes): allow berglas_files in predefined steps

kubernetes/resources/honeydipper-job.yaml.tmpl
The `securityContext` is originally only supported in `script_types`. This is to add the ability to override that in the job steps.
=> feat: override securityContext in k8s job step

github.yaml
These two functions are useful when we need to automatically sync between branches.
=> feat(systems): add github updateRef mergeBranch functions

kubernetes/resources/honeydipper-job.yaml.tmpl
Right now, the env value only supports string and map. We need to be able to support numbers, boolean as well.
=> fix: support kubernetes job env value types

gcloud/gke.yaml, kubernetes/workflows.yaml, slack/systems.yaml
The predefined environment variables and volumes are not supported in
step definitions, only supported in global env and volumes. This should
add the support in the step definitions.
Also with some GKE log and job url improvements
* add cursor time to k8s log url
* correct namespace for job url
=> fix: support predefine_ var and vol in steps

kubernetes/workflows.yaml
Should not assume the variable types are string, instead anything not a map should be treated the same way.
=> fix: allow different types of environment variable

codeclimate/systems.yaml, jira.yaml, opsgenie.yaml, pagerduty.yaml, slack/systems.yaml, web.yaml, webhook.yaml
**Description:**
- send charset=utf-8 with all Content-Type headers
- Slack got unhappy
=> fix: send charset=utf-8 with all Content-Type headers

slack/systems.yaml
update_message should be able to send a new message if the `ts` is not found, meaning no message to update. This is useful when updating status messages with errors.
=> fix: update_message should handle both update and new messages

slack/systems.yaml
In case there is no initial message, an update message can set the ts so it can be updated in the future.
=> fix: update_message also can set ts

kubernetes/contexts.yaml
berglas 2.0.0 seems broken related to logging level handling.
=> fix: pin berglas to 1.0.3

pagerduty.yaml
merge modifiers are not supported in function exports.
=> fix: use merge modifier in wf

kubernetes/resources/honeydipper-job.yaml.tmpl
`backoffLimit` set to 0 will result in the failed pod getting deleted. We would like to keep it for troubleshoot.
=> fix: k8s job failed pod missing

circleci.yaml
The create context API accepts both id or slug, but the property name must be matching. The api document has a hidden tab that show the example of using the alternatives, but easy to miss.
=> fix: circleci api put context id vs slug

daemon.yaml
Daemon and drivers can take advantages of cache through RPC calls.
=> feat: cache driver to allow use cache with RPC
