honeydipper/honeydipper-config-essentials

daemon.yaml, datadog/init.yaml, gcloud/drivers.yaml, kubernetes/driver.yaml, web.yaml, webhook.yaml
This should go hand-in-hand with honeydipper/honeydipper#66
=> refactor(driver): using binary builtin driver type

workflow_helper.yaml
=> feat(pipe): allow using work_data workflow internally and externally

workflow_helper.yaml
This should fix the nightly non-error messages.
=> is_error value could be a string

workflow_helper.yaml
Made a common mistake, have to make sure to compare the same type of values
=> is_error could be string value

github.yaml
The endpoint was missing `/comments`
=> fix(github): correct issue comments api endpoint

kubernetes/workflows.yaml
Fixes #17 
Fixes #18 
Fixes #19 (still not working, requires kubernetes go library support)
=> Enhancements for run_kubernetes workflow

github.yaml
=> Add github getContent method

slack/workflows.yaml, workflow_helper.yaml
Reverts honeydipper/honeydipper-config-essentials#44
=> Revert "feat: translate channel names to private chat IDs"

slack/workflows.yaml
Reverts honeydipper/honeydipper-config-essentials#50
=> Revert "feat: allow slashcommands to use contexts"

slack/workflows.yaml
=> feat: allow slashcommands to use contexts

kubernetes/contexts.yaml, kubernetes/resources/honeydipper-job.yaml.tmpl
Required by honeyscience/honeydipper-config#224 and honeyscience/honeydipper-config#225
=> feat: improvements on k8s job predefined steps involving secret injection

gcloud/drivers.yaml
Requires honeydipper/honeydipper#283, and new release
=> feat(gcloud): spanner native backup through gcloud-spanner driver

jira.yaml
* fix export indention error
* add links to the export
* make jira_domain_base configurable
* update API version from 2 to 3
=> fix(jira): export indention error

jira.yaml
* accept a complete ticket structure instead of indivdual fields
* allow components and labels and more
* updated inline documents
=> feat(jira): adjust createTicket parameters

.circleci/config.yml, api_auth.yaml, daemon.yaml, init.yaml, tests/api_auth_tests.yaml
* feat(auth): using casbin authorization framework
* test: adding tests for auth rules
=> feat(auth): using casbin authorization framework

opsgenie.yaml
Create driver to get opsgenie user's contact details
ie. phone number
=> feat(opsgenie): Add method to get user's contact details (OPS-2336)

github.yaml
Remove a repo from an installed github application
=> feat(github): remove repo from github app (OPS-2590)

slack/workflows.yaml
Update terminology for allowed channels
=> style(workflows): switch terminology for allowed channels

slack/contexts.yaml, slack/workflows.yaml, workflow_helper.yaml
* customizable `slash_notify`
* support detailed help for individual commands
* granular control on error notifications
=> feat(slack): improve slashcommand handling

gcloud/dataflow.yaml, gcloud/gke.yaml, gcloud/init.yaml
Make it easier to work with dataflow jobs.
=> feat: add functions and docs to gcloud-dataflow systems

codeclimate/init.yaml, codeclimate/systems.yaml, codeclimate/workflows.yaml
=> feat: codeclimate integration

init.yaml
Add Code Climate integration init.yaml
=> fix(codeclimate): add codeclimate init

codeclimate/systems.yaml, codeclimate/workflows.yaml
Add optional CC_TEST_REPORTER_ID env var when adding a private repo
=> feat(codeclimate): add CC_TEST_REPORTER_ID env var

kubernetes/resources/honeydipper-job.yaml.tmpl, kubernetes/workflows.yaml
Changes included:
- update k8s job template to support resources and parallelism
- update documentation
=> feat: add resources and parallelism for k8s job config

kubernetes/resources/honeydipper-job.yaml.tmpl, kubernetes/system.yaml, kubernetes/workflows.yaml
- allow creating job from a cronjob definition
- allow override creator label
These features are added sometime ago, but forgot to PR them.
=> feat: enhancements to run k8s jobs

slack/systems.yaml, workflow_helper.yaml
* allow update previous message with `ts` property
* allow update interactive message with `response_url`
=> feat: allow update previous slack message

github.yaml
We can trigger a workflow when a commit status changes.
=> feat(github): injest commit status update events

slack/systems.yaml
If the return comes with an error, we will report it.
=> fix: slack error should be reported

gcloud/drivers.yaml
* adding gcloud-logging driver
* k8s createPVC and deletePVC
=> feat: adding gcloud-logging driver

kubernetes/resources/honeydipper-job.yaml.tmpl, kubernetes/system.yaml
Requires #159 
Needs rebase after #159
=> feat: support pod securityContext and workdir_volume

.circleci/config.yml, api_auth.yaml, daemon.yaml, tests/api_auth_tests.yaml
auth-gcp-iap provider will take over the authentication if requests are coming from IAP.
=> feat: support matching provider in rules

gcloud/gke.yaml
**Description**
- just pass startTime to the stackdriver url
- It seems like adding the time range makes the "Stream Logs" function not work correctly
=> feat: just pass startTime to the stackdriver url

pagerduty.yaml
=> fix: get on call by tags instead of by name

slack/systems.yaml
Reverts honeydipper/honeydipper-config-essentials#171
=> Revert "fix: update_message also can set ts"

contexts.yaml, github.yaml, slack/systems.yaml
The new AI chatting feature uses threaded conversations.
related to honeydipper/honeydipper#638
=> feat: slack support sending message in thread

slack/rules.yaml, slack/systems.yaml
Enable slack driver to receive events such as message events, mention events etc.
=> feat: slack driver support slack events api

slack/systems.yaml
- separate url_verfiaction event from other events
- typo in function parameters
- generic slack api function
=> fix: various slack_bot fixes
